FROM ubuntu:12.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y python-software-properties
RUN add-apt-repository ppa:fkrull/deadsnakes
RUN apt-get clean all && apt-get -y update
#RUN apt-get -y install python2.4 python2.6 python2.7 python3.4
RUN apt-get -y install python2.4
RUN apt-get -y install python-httplib2 python-keyczar python-paramiko python-setuptools python-software-properties openssl make python-pip sudo rsync subversion git openssh-server supervisor mercurial rubygems
RUN pip install tox PyYAML Jinja2 sphinx

RUN mkdir /var/run/sshd
RUN mkdir ~/ansible_testing

EXPOSE 22

CMD ["/bin/bash"]

