FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install python-software-properties
RUN add-apt-repository ppa:fkrull/deadsnakes
RUN apt-get clean all && apt-get -y update
apt-get install -y \
    python2.4 \
    python2.6 \
    python2.7 \
    python3.4 \
RUN apt-get -y install python2.7 python-yaml python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools python-software-properties openssl
